### PR TITLE
Uniform zeros like syntax

### PR DESCRIPTION
**Pull request by aminya**
```julia
julia> Uniform(Float32,-1,1)
Uniform{Float32}(a=-1.0f0, b=1.0f0)
```

### CODE REVIEW

**Comment by matbesancon** [comment]
The feature is interesting. Wasn't there anything already in the package doing this?
Before merging that, could you add a bunch of tests and docstring to Uniform explaining the behaviour?

**Comment by andreasnoack** [comment]
I think `Uniform{Float32}(-1, 1)` would be more in line with how we typically do this, e.g.
```julia
julia> Complex{Float32}(1,1)
1.0f0 + 1.0f0im
```

**Comment by aminya** [comment]
> 
> 
> I think `Uniform{Float32}(-1, 1)` would be more in line with how we typically do this, e.g.
> 
> ```julia
> julia> Complex{Float32}(1,1)
> 1.0f0 + 1.0f0im
> ```

That is one of the APIs that I specified in this issue. However, we need to first fix the type stability. The issue is bigger than the API

**Comment by aminya** [comment]
Proceeded by https://github.com/JuliaStats/Distributions.jl/pull/1045

**Pull request closed without merging**
