### PR TITLE
fix noncentral-T

### PR DESCRIPTION
**Pull request by Ph0non**
fix noncentral-T for negative noncentrality parameter #462

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
This is a great change. Can we get some tests?

**Comment by Ph0non** [comment]
I didn't understand. Is this irony? The change is really small and didn't lead to any unsuspected result, because in `noncentralt.jl` happens nothing spectacular with λ.

In my local branch it works as expected to calculate the UCL of an .95-percentile.

**Comment by johnmyleswhite** [comment]
No, it's not irony. Please write a test.

**Comment by jiahao** [comment]
Every change is appreciated. If you had an example which led you to discover this bug, it would be valuable to put that example in the test suite, so that future code changes won't break it by accident.

**Comment by nalimilan** [comment]
Welcome, and don't worry, people are seldom sarcastic here. :-)

While you're at it, it would be great to have a more explicit commit message. Just saying what you mentioned in https://github.com/JuliaStats/Distributions.jl/issues/462 about the distribution's support would be good.

**Comment by Ph0non** [comment]
I'm not very familiar with git. As I see, I need to amend this commit, to edit the message. Is this also possible, if I commit over github?

Would this be enough for a test?
```
using Distributions
using Base.Test

# non-central T-Distributions
ν = 50
λ = -5

d = NoncentralT(ν, λ)
@test_throws MethodError NoncentralT(ν, complex(λ))
@test d == typeof(d)(params(d)...)
@test_approx_eq_eps mean(d) -5.0766 1e-5

λ = 5
d = NoncentralT(ν, λ)
@test_approx_eq_eps mean(d) 5.0766 1e-5

λ = 0
d = NoncentralT(ν, λ)
@test var(d) == var(TDist(ν))
```

**Comment by kleinschmidt** [comment]
That's fine, you'll just have to "git push --force" because you've overwritten a commit you already pushed. Use this power with great caution :)

**Pull request closed without merging**
