### PR TITLE
Fix call to promote_eltype

### PR DESCRIPTION
**Pull request by sethaxen**
`promote_eltype` is not exported by Julia Base.

### CODE REVIEW

**Comment by ararslan** [comment]
Great, thanks! Could you add a test that would have error if not for this change?

**Comment by matbesancon** [comment]
Looks good, is there another test that should be done, a bit more specific on the change done?

**Comment by matbesancon** [comment]
bump @sethaxen

**Comment by matbesancon** [comment]
bump here

**Comment by matbesancon** [comment]
Thanks!

**Pull request merged**
