### PR TITLE
fix notation in laplace.jl docstring

### PR DESCRIPTION
**Pull request by JeffFessler**

### CODE REVIEW

**Comment by matbesancon** [comment]
I'm fine to keep these conventions (better than being inconsistent), but [a great place of knowledge](https://en.wikipedia.org/wiki/Laplace_distribution) uses `b` instead of beta

**Comment by JeffFessler** [comment]
I am fine with `b` too - feel free to revert.  I think I saw \beta in some places and \theta in others (and b in others) so I was just pursuing self-consistency.
I looked in several probability texts on my shelf and most of them write it in terms of \lambda = 1/b and one book used \alpha=1/b so there is no standard out there it seems. Cheers.

**Comment by matbesancon** [comment]
Just waiting for another opinion and this is merged, thanks for the contribution!

**Comment by matbesancon** [comment]
(Travis is failing while #836 not merged)

**Comment by simonbyrne** [comment]
Should it be sigma?

**Comment by matbesancon** [comment]
doesn't seem to be the convention for Laplace

**Comment by simonbyrne** [comment]
we should be consistent for all location/scale families:
- Cauchy
- Logistic
- SymTriangular
- Biweight
- Triweight
- Epanechnikov
- Cosine

**Comment by matbesancon** [comment]
This part will be simpler for the construction with #823, but without it, it may be dangerous to require a parameter which is not the one usually taken

**Comment by simonbyrne** [comment]
I’m no sure what you mean?

**Comment by JeffFessler** [comment]
I just noticed that cauchy.jl has similar inconsistencies in its docstring.
Perhaps @simonbyrne is suggesting that all docstrings should be made more self consistent.
I agree with the goal of self consistency within each docstring, but I also agree with @matbesancon that trying to unify notation across all distributions could be problematic.  For example, I see that the docstring for  cauchy.jl uses \mu and \sigma but that is nonstandard and possibly misleading notation because Cauchy does not have a mean or variance.

**Comment by matbesancon** [comment]
I'd be for keeping letters different from `mu, sigma` when the location and scale parameters do not represent mean, std directly

**Comment by matbesancon** [comment]
restarted the build, merging as everything goes green

**Comment by matbesancon** [comment]
@simonbyrne can you restart appveyor here?

**Pull request merged**
