### PR TITLE
fix rank doc

### PR DESCRIPTION
**Pull request by johnczito**

### CODE REVIEW

**Comment by matbesancon** [comment]
@johnczito this should be `LinearAlgebra.rank` I think

**Comment by johnczito** [comment]
That only works if you add `using LinearAlgebra` to `docs/make.jl`. But it's the same as this (in my local build, anyway).

**Comment by matbesancon** [comment]
`import LinearAlgebra` in the build doc would do it yes, I find it clearer to know where the functions are defined

**Comment by johnczito** [comment]
Agreed. In the built docs it still displays `LinearAlgebra.rank`, not `Distributions.rank`. I figured loading `LinearAlgebra` into `make.jl` would be overkill. But if you also want it to read `LinearAlgebra.rank` in the doc source, then I'm happy to do it.

**Comment by matbesancon** [comment]
If the doc displays correctly then it's fine

**Comment by matbesancon** [comment]
thanks!

**Pull request merged**
