### PR TITLE
added mle implementation for beta distribution fitting

### PR DESCRIPTION
**Pull request by amgad-naiem**
MLE fitting for beta distribution using dL/dalpha = 0 & dL/dbeta = 0 nonlinear system of equations solving (NLsolve)

### CODE REVIEW

**Comment by kmsquire** [comment]
What are people's thoughts on adding a dependency on `NLsolve`?

**Comment by andreasnoack** [comment]
I'd prefer that we factor out estimation/fitting into a separate package instead of extending the support here and add a new dependency. `Distributions.jl` is already quite heavy and estimation is a big area. It is also more likely that people will disagree about how to *fit* distributions.

**Comment by simonbyrne** [comment]
Agreed, I think a separate package would be appropriate for now.

**Comment by kmsquire** [comment]
Sounds good.  Any thoughts on the granularity/name?  `DistributionFitting.jl` or 
`DistributionMLE.jl`?

**Comment by tkelman** [comment]
+1 for spelled out words like Fitting rather than the acronym MLE

**Comment by johnmyleswhite** [comment]
+1 for DistributionFitting since we already have support for MAP estimation and I've often wished that we had method of moments fitting as well.

**Comment by simonbyrne** [comment]
FWIW, it should be possible to do this via Newton's method or something similar, in which case I would be happy to include it (I just don't want to add NLSolve as a dependency).

**Comment by andreasnoack** [comment]
I thought we reached consensus on delegating fitting methods to a separate package. To me, it is a good separation of tasks it also separates the dependency requirements.

**Comment by simonbyrne** [comment]
I agree, but we already have some fitting methods in Distributions, so it would be useful to have some standard criteria. I think a useful one would be that it doesn't add any further dependencies.

**Comment by andreasnoack** [comment]
It's not urgent but I think it would make sense to migrate the existing fitting methods here to the new package as well.

**Comment by amgad-naiem** [comment]
@simonbyrne NLSolve is using Newton's method and I have not found any other package other that NLSolve for doing that.

**Comment by johnmyleswhite** [comment]
I think the expectation is that you'll write the Newton's method code for hand, which is what we've done in the past for other distributions.

**Pull request closed without merging**
