### PR TITLE
Bump FillArrays dep

### PR DESCRIPTION
**Pull request by willtebbutt**
Also bumps the patch version so we can tag a release.

### CODE REVIEW

**Comment by willtebbutt** [comment]
@matbesancon hopefully this is trivial to review.

**Comment by matbesancon** [comment]
sorry, crazy under water here and haven't looked at Distributions for a long time, we should make you a maintainer for this sort of things

**Comment by willtebbutt** [comment]
Thanks for sorting this out!

**Comment by matbesancon** [comment]
No problem, if you want to go through other PRs and review, if some are ready to merge feel free to ping me

**Comment by willtebbutt** [comment]
As much as I would love to, I'm also somewhat swamped -- just trying to propagate updates through the ecosystem so that I can upgrade the GP ecosystem 😂

**Comment by devmotion** [comment]
Just as a note: another unreleased commit on master that ended up in this release was marked as "BREAKING".

**Comment by willtebbutt** [comment]
😬

**Comment by andreasnoack** [comment]
I just checked the `compare` view and it's not easy to see neither the "breaking" label not the [BREAKING] part I added to the title. I'm not sure how to make it more visible. Any ideas/

**Comment by devmotion** [comment]
Maybe try to enforce that the version number is updated in PRs? This might not only make it less likely that it is updated incorrectly later on (in particular, if a different maintainer makes the release) but would also allow to make a release directly after the PR is merged.

**Comment by willtebbutt** [comment]
Possibly `Distributions` should consider separating out `master` from `DEV-new-minor-version` -- it would be a shame if breaking changes held up compat updates etc.

**Pull request merged**
