### PR TITLE
Change order of arguments in `expectation`

### PR DESCRIPTION
**Pull request by devmotion**
I noticed in https://github.com/JuliaStats/Distributions.jl/pull/1414 that the order of arguments in `expectation` does not follow the general Julia recommendations and style. IMO the function should be the first argument since this would also allow to use the `do` syntax. The PR fixes this issue.

Additionally, I wonder if `expectation` should be exported.

### CODE REVIEW

**Comment by mschauer** [comment]
Not really a fan of having numerical integration in `Distributions.jl`, not sure if worth fixing it and even exporting it. Similar to want @matbesancon says here: https://github.com/JuliaStats/Distributions.jl/issues/968#issuecomment-535432617

**Comment by devmotion** [comment]
I understand these concerns and I don't think we *have* to export it. However, I think it is just a fallback (and the natural one), so no guarantees on accuracy and/or ineffeciency. Additionally, `expectation` has existed for more than 9 years: https://github.com/JuliaStats/Distributions.jl/commit/87eca10bbcbab484260f1b96c7d3a3fb60a41aef

QuadGK is also used in other places, e.g., for computations with the Chernoff distribution and the non-central hypergeometric distribution.

**Comment by mschauer** [comment]
Yeah, we don't need to remove it, but I am fine with it to continue living under the stairs with the wrong argument order (I agree that the current order bad for `do`-operations)

**Comment by devmotion** [comment]
So you think we shouldn't fix the order internally and be able to use `do` syntax internally? This PR does not export `expectation`, it was only a question that occurred to me.

**Comment by mschauer** [comment]
In any case it seems that people don't rely much on it outside: https://juliahub.com/ui/Search?q=Distributions.%2aexpectation&type=code&r=true

**Comment by devmotion** [comment]
The PR is not intended for othee packages or users.

**Comment by mschauer** [comment]
No harm is done by checking if people are using unexpected function and if changing them will break that code.

**Review by mschauer — APPROVED** [review]
Ok, let's do it, as we are able to provide update path via the deprecation of the old order.

**Pull request merged**
