### PR TITLE
fix kurtosis

### LINKED ISSUE #839: Functions for kurtosis excess are backwards
The functions 'isplatykurtic' and 'isplatykurtic' are backwards:

**-**_isleptokurtic(d)_: Return whether d is leptokurtic (i.e kurtosis(d) < 0)  ->  **Should be: kurtosis(d)>0**
**-**_isplatykurtic(d)_:  Return whether d is platykurtic (i.e kurtosis(d) > 0)  ->   **Should be: kurtosis(d)<0**

http://mathworld.wolfram.com/KurtosisExcess.html

### PR DESCRIPTION
**Pull request by matbesancon**
Fixes #839

### CODE REVIEW

**Comment by andreasnoack** [comment]
An alternative is to deprecate these. I doubt that anybody uses them.

**Comment by matbesancon** [comment]
still useful when you have some doubts about conventions (which is which)

**Comment by mschauer** [comment]
We could test
```
@test isplatykurtic(Bernoulli(0.5))
```

**Comment by matbesancon** [comment]
tests added in last version, with Normal for meso and Laplace for lepto.

**Pull request merged**
