### PR TITLE
tvtcdf: cleanup and tests

### PR DESCRIPTION
**Pull request by wildart**

### CODE REVIEW

**Comment by kmsquire** [comment]
Thanks!  Would you be able to add a quick test that exercised this code path?

**Comment by wildart** [comment]
It crashed when `using Distributions` was called. I guess something happened in nightly build.

**Comment by kmsquire** [comment]
Thanks!  @andreasnoack should be the one to pull the trigger here.

**Comment by andreasnoack** [comment]
@wildart Thanks. I'm still confused why this has only surfaced now.

**Comment by julian-gehring** [comment]
Thanks for the quick fix! Can 50d4a9c590660a41b0edf164dda48c3c9ee8d17d be tagged as a new version?

**Comment by andreasnoack** [comment]
Yes. Since distributions actually does load right now it is probably a good idea to tag a version. I'll do that.

**Comment by simonbyrne** [comment]
Actually, can we wait until the tests pass? We should also tag a new StatsBase, and bump the requirements.

**Comment by andreasnoack** [comment]
Yes that is the right way to proceed. I think the deprecation warnings are making tests hang. There has been something weird things going on with `Tasks` lately. I'll update StatsBase with `@compat`s to get rid of the warnings and hopefully that will make the tests pass.

**Comment by andreasnoack** [comment]
@simonbyrne Oh. You just did that.

**Comment by simonbyrne** [comment]
Yep, I'm just about to open a PR.

**Comment by simonbyrne** [comment]
I can update the REQUIRE and tag Distributions.jl as well.

**Comment by andreasnoack** [comment]
Great. Then I'll just return to other duties.

**Comment by simonbyrne** [comment]
Okay, should be done now, sorry about the delay.

**Pull request merged**
