### PR TITLE
Fix fit(Laplace) for changes to StasBase.mad

### PR DESCRIPTION
**Pull request by andreasnoack**
We really need some automated way of testing downstream packages when we tag a new release.

### CODE REVIEW

**Comment by ararslan** [comment]
We could add something like
```bash
julia -e 'for dep in Pkg.dependents("Distributions") Pkg.test(dep) end'
```
to the .travis.yml script. That will make Travis times *skyrocket* though.

**Comment by johnmyleswhite** [comment]
The R community addresses this by e-mailing all dependent package authors before tagging a new release. But their releases are far more spread out.

**Comment by KristofferC** [comment]
@ararslan  Could just do it locally before tagging the release?

**Comment by andreasnoack** [comment]
I'll try to do that now. I've access to some beefy machines and with `pmap` it might be possible to finish in reasonable time although it's 89 packages.

**Comment by KristofferC** [comment]
Maybe run it on the last version as well to get rid of spurious failures?

**Comment by ararslan** [comment]
@KristofferC Sure, I was just thinking more in terms of identifying breaking changes in PRs before they're merged.

**Comment by andreasnoack** [comment]
Just tried this for this branch and there is some work to do if we want to look into all problems in dependent packages
```jl
julia> r = pmap(foo, Pkg.dependents("Distributions"), on_error=identity)

julia> mapreduce(t -> isa(t, Exception), +, r)
86
```

**Comment by tkelman** [comment]
So Distributions master is massively broken for almost every package that uses it? This should be a blocker on tagging any new version of the package then. 0.10.2 was made off of a branch for this reason, and that branch should probably be used to make a not-so-breaking 0.10.3 where you backport only the deprecation and test-related fixes, without the enormous rewrite.

**Comment by andreasnoack** [comment]
I'm pretty sure my result in https://github.com/JuliaStats/Distributions.jl/pull/532#issuecomment-246552504 is nonsense. Testing packages in parallel is probably not possible.

**Comment by tkelman** [comment]
Yeah, in some discussions with @ararslan we dug up the PkgEval results from the day that 0.10.1 was tagged, and there's some breakage but it's a handful of package, not all of them.

**Pull request merged**
