### PR TITLE
Add syntactic sugar for LocationScale

### PR DESCRIPTION
**Pull request by briochemc**
In line with how affine transformations can be applied to `MvNormal` (PR https://github.com/JuliaStats/Distributions.jl/pull/1051), this PR uses the already available machinery of `LocationScale` to allow affine transformations of `ContinuousUnivariateDistribution`s, so that one can do, for example:

```julia
julia> d = LogNormal(0.0, 1.0)
LogNormal{Float64}(μ=0.0, σ=1.0)

julia> 2 * d + 1
LocationScale{Float64,LogNormal{Float64}}(
μ: 1.0
σ: 2.0
ρ: LogNormal{Float64}(μ=0.0, σ=1.0)
)
```

This PR follows the discussions in issue #1214.

On top of the syntactic sugar for affine transformations, this PR also specializes `LocationScale(μ,σ,ρ::LocationScale)` so that composed calls to `LocationScale` don't return nested `LocationScales` (as suggested in issue #1214).

The `LocationScale` tests are the same up to a tiny difference (see below) but are now written in a more functional way so that hopefully adding more distributions will be more straightforward (as suggested in issue #1214).

I think the added tests cover all the new functions. But note the tiny difference: I had to change the `atol=1e-100` of the `ccdf` test to `atol=1e-15` for it to pass, since this was off by the last `Float64` digit for the composed `ScaleLocation` test distribution...

Note there is a leftover small fix for `Uniform` from PR https://github.com/JuliaStats/Distributions.jl/pull/1133 ~and another change in `LogNormal` that I guess comes from me manipulating my local repo the wrong way~ [EDIT: This has been reverted in the last commit]. Please advise on what to do about those!

### CODE REVIEW

**Comment by briochemc** [comment]
Gentle bump!

**Review by andreasnoack — COMMENTED** [review]
Wouldn't it be a good idea to add methods for `LocationScale` that would fuse the location and scale instead of nesting?

**Comment by briochemc** [comment]
Yes, I think that's what 

https://github.com/JuliaStats/Distributions.jl/blob/4e026ee9204b3d6f8826028d58c20dfd1628d363/src/univariate/continuous/locationscale.jl#L42

is supposed to do in this PR IIRC, but maybe there's a bug there?

**Comment by andreasnoack** [comment]
Ah. I misread that definition. Then I think this one is good to go.

**Pull request merged**
