### PR TITLE
[WIP] Add drop in replacements for Rmath functions

### PR DESCRIPTION
**Pull request by jayvn**
Currently exporting : 
`qnorm`,  `pnorm`,  `rnorm`.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I'm pretty sure we don't want to support the R API here. People should generally prefer the existing API provided by `Distributions`, i.e. `pdf`, `quantile`, `cdf`, and `norm`.

**Comment by jayvn** [comment]
OK, not the whole R API, but I thought it'd be a lot more convenient to just do things like `qnorm(.05)` rather than `cdf(Normal(), .05)` especially when writing long equations. I agree that the latter is more readable.

**Comment by andreasnoack** [comment]
I think providing such an API should be a task for a different package if really needed.

**Comment by jayvn** [comment]
Understood. Thanks for the response.

**Comment by matbesancon** [comment]
Closing this as discussed

**Pull request closed without merging**
