### PR TITLE
Upgrade to SpecialFunctions 0.8

### PR DESCRIPTION
**Pull request by andreasnoack**
Continuation of #891

### CODE REVIEW

**Comment by andreasnoack** [comment]
I think it might be timing out because of the depwarns from StatsFuns. We can try testing again once https://github.com/JuliaStats/StatsFuns.jl/pull/77 has been included in a release.

**Comment by matbesancon** [comment]
I don't get how CI just froze (at a consistent point), infinite loop? There are still some warnings around

**Comment by andreasnoack** [comment]
I believe the remaining warnings are all from StatsFuns. My suspicion was that it might be calling a deprecated method many many times and deprecations are really slow. I'll look more carefully once the new StatsFuns release is out.

**Comment by andreasnoack** [comment]
I think it was the deprecations. It looks like things are working now.

**Comment by andreasnoack** [comment]
@matbesancon I'm not sure how much stuff has accumulated on master so I'll let you handle the release but it would probably be good to get one out fairly soon since Distributions has hold back package updates for a while because of the SpecialFunctions restriction.

**Comment by oschulz** [comment]
Cool! Will you guys tag a Distributions v0.21.6 with this?

**Pull request merged**
