### PR TITLE
Add documentation for Poisson Binomial distribution

### PR DESCRIPTION
**Pull request by nignatiadis**
Was thinking of implementing the Poisson Binomial distribution myself when I noticed it had already been done :).

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
LGTM. Is the code tested enough that we're comfortable making it public?

**Comment by nignatiadis** [comment]
Hmm, @chrodan implemented it (see #346), so he would be most suited to answer this question. The case where the Poisson Binomial just reduces to the Binomial distribution is already tested thoroughly though.

It would also be easy to add some more tests, e.g. by comparing the CDF calculated by the Fourier transform (implemented here) to the CDF calculated by the (numerically unstable) recursive method for small K.

**Comment by chrodan** [comment]
In #383 I added tests for cases where the Poisson-Binomial distribution does not reduce to the Binomial distribution. The tests rely on the Binomial distribution but I guess that is acceptable.

**Comment by johnmyleswhite** [comment]
Thanks for doing this!

**Pull request merged**
