### PR TITLE
Updates for 0.7

### LINKED ISSUE #697: compilation of nightly fails with RangeGeneratorInt message
My PR https://github.com/JuliaStats/Distributions.jl/pull/695 compiles fine on v0.6 but on nightly it fails with 

**ERROR: LoadError: LoadError: LoadError: UndefVarError: RangeGeneratorInt not defined**

The issue appears to arise in Categorical.jl, to which I have not made changes.

What gives?

### PR DESCRIPTION
**Pull request by ararslan**
Supersedes #700, which is stalled on unmerged Compat changes. Fixes #697.

### CODE REVIEW

**Comment by ararslan** [comment]
I pretty much just want to get the package to load on 0.7 at this point. It still emits an apocalyptic amount of deprecation warnings but those can be addressed separately.

**Comment by ararslan** [comment]
Hm, having a hard time figuring out what exactly is causing the error.

**Comment by dmbates** [comment]
Sorry about the request for a review by @lindahua That was accidental.

**Comment by Nosferican** [comment]
Any updates on this?

**Comment by ararslan** [comment]
Not really, thanks for the reminder. I'll revisit this soon.

**Comment by Nosferican** [comment]
Besides the cryptic error it seems to be working for the most part...

**Comment by ararslan** [comment]
Issue in StatsBase?
```
MethodError: no method matching binominvcdf(::Tuple{Expr,Expr}, ::Float64)
Closest candidates are:
  binominvcdf(!Matched::Real, ::Real, !Matched::Real) at /home/travis/.julia/v0.7/StatsFuns/src/rmath.jl:74
quantile at /home/travis/.julia/v0.7/Distributions/src/univariates.jl:547
#test_samples#59 at /home/travis/.julia/v0.7/Distributions/src/testutils.jl:109
test_samples at /home/travis/.julia/v0.7/Distributions/src/testutils.jl:87
```

**Comment by juliohm** [comment]
@ararslan have you figured out where the error above is coming from? I am so eager to port my packages to Julia v0.7 and forget about Julia v0.6 :blush:

**Comment by ararslan** [comment]
Nope, not sure what the deal is yet.

**Comment by ararslan** [comment]
PDMats dropped support for 0.6 and we're relying on some functionality that changed between PDMats releases, so I think we're going to have to drop 0.6 support here as well.

**Comment by ararslan** [comment]
I've made some significant progress here, but it still doesn't quite work yet. I'll be able to look more at this next week.

**Comment by appleparan** [comment]
Any updates for 0.7-alpha?

**Comment by tpapp** [comment]
Friendly ping:  now that some dependencies got updated to v0.7 (eg PDMats), I wonder if the maintainers could please try tackling this again when time allows. With the latest commits in this PR, the package loads cleanly, and the tests seem to be running (but I never let them complete, as they seem to take forever, probably because of deprecations).

**Comment by ararslan** [comment]
Sorry for not following up more on this, I've been busy with a million other things. With #725, we should be in better shape here, I think.

**Comment by simonbyrne** [comment]
Included as part of #729

**Pull request closed without merging**
