### PR TITLE
Faster, more accurate Poisson Binomial PMF

### PR DESCRIPTION
**Pull request by bdeonovic**
I have done a lot of research in evaluating poisson binomial pmf in last 3 years. The simplest and fastest continues to be the recursive formula. I've cited Thomas & Taub (1982) but it predates this article as well because it is related to evaluating the elementary symmetric function. The Hong (2013) article does a very bad job at evaluating and comparing their method 

```julia
julia> x = [3.5118, .6219, .2905, .8450, 1.8648]
julia> p = big.(x) ./ (1 .+ big.(x))
julia> @benchmark poisbin_sum_taub(p)
BenchmarkTools.Trial: 
  memory estimate:  10.20 KiB
  allocs estimate:  230
  --------------
  minimum time:     7.075 μs (0.00% GC)
  median time:      7.525 μs (0.00% GC)
  mean time:        9.559 μs (12.27% GC)
  maximum time:     2.087 ms (66.47% GC)
  --------------
  samples:          10000
  evals/sample:     4

julia> @benchmark Distributions.poissonbinomial_pdf_fft(p)
BenchmarkTools.Trial: 
  memory estimate:  188.90 KiB
  allocs estimate:  4155
  --------------
  minimum time:     515.800 μs (0.00% GC)
  median time:      523.201 μs (0.00% GC)
  mean time:        558.614 μs (3.83% GC)
  maximum time:     9.248 ms (62.80% GC)
  --------------
  samples:          8935
  evals/sample:     1

julia> sum(abs.(poisbin_sum_taub(p) .- naive_sol))
1.106509096121475717627626332421301195049237546693398552456162007115350824780186e-77
julia> sum(abs.(Distributions.poissonbinomial_pdf_fft(p) .- naive_sol))
3.197437330491599664330118659436447055371737441489833207203143282015769955768403e-17
```
One method which does truly scale better than the recursive algorithm is Biscarri (2018), but it is a lot more involved but I do have it implemented in julia in a separate package right now. In simulation study you can see that it has comparable error rate, but is faster than the recursive algorithm for long inputs (see figure below where DFT-CF is Hong (2013), Taub is recursive algorithm implemented in this PR, and DC-FFT is Biscarri (2018)).

pmf_sim

### CODE REVIEW

**Comment by johnczito** [comment]
Thanks! Haven't looked at this in detail yet, but I'm in favor of keeping the old implementation around so you can write some unit tests comparing the two.

**Comment by bdeonovic** [comment]
No problem, probably tomorrow. its a nice day when a simple for loop gives 50x speedup to a function :)

**Comment by bdeonovic** [comment]
What kind of tests do you want to see?

**Comment by johnczito** [comment]
Just check that `poissonbinomial_pdf` and `poissonbinomial_pdf_fft` give approximately the same thing.

**Comment by bdeonovic** [comment]
Added some additional tests, but I should point out that my PR had alread passed the tests that were implemented before for poisson binomial

**Comment by bdeonovic** [comment]
Should be ready for merge after review.

**Comment by johnczito** [comment]
This looks good to me (not super familiar, though). Why don't we want the Biscarri version right now?

**Comment by bdeonovic** [comment]
I can put it in, its just a lot more involved

**Comment by johnczito** [comment]
Up to you. I'll merge this in 24 hours if there is no other feedback.

**Review by johnczito — APPROVED** [review]

**Comment by bdeonovic** [comment]
@johnczito The biscarri method requires a solid working fft filter function. In my package I imported the corresponding functions from the DSP package. I don't get the same speed up with my own written fft filter. 

Below  esf_sum is the recursive algorithm implemented in this PR, esf_dc_group is the biscarri method with my own fft filt code, and esf_dc_fft is the biscarri method with the fft filt from DSP package. I think using the simple recursive algorithm I have already provided is enough as it won't require any more package dependencies and the speed up is not that significant. I propose to go ahead and merge. 

```julia
julia> x = exp.(randn(15000))
julia> @benchmark esf_dc_group(x, 4)
BenchmarkTools.Trial: 
  memory estimate:  1.95 MiB
  allocs estimate:  9
  --------------
  minimum time:     175.359 ms (0.00% GC)
  median time:      178.497 ms (0.00% GC)
  mean time:        181.368 ms (0.07% GC)
  maximum time:     200.614 ms (0.00% GC)
  --------------
  samples:          28
  evals/sample:     1

julia> @benchmark esf_sum(x)
BenchmarkTools.Trial: 
  memory estimate:  117.33 KiB
  allocs estimate:  2
  --------------
  minimum time:     44.550 ms (0.00% GC)
  median time:      44.788 ms (0.00% GC)
  mean time:        45.534 ms (0.00% GC)
  maximum time:     53.893 ms (0.00% GC)
  --------------
  samples:          110
  evals/sample:     1

julia> @benchmark esf_dc_fft(x,4)
BenchmarkTools.Trial: 
  memory estimate:  2.41 MiB
  allocs estimate:  60
  --------------
  minimum time:     31.536 ms (0.00% GC)
  median time:      32.574 ms (0.00% GC)
  mean time:        33.238 ms (0.61% GC)
  maximum time:     44.119 ms (11.66% GC)
  --------------
  samples:          151
  evals/sample:     1
```

**Pull request merged**
