### PR TITLE
Change r parameter from Int to Float64

### PR DESCRIPTION
**Pull request by augustinyiptong**
First time github user, so i would appreciate any feedback.

I need to use a negative binomial distribution with a float for parameter r. https://github.com/JuliaStats/Distributions.jl/issues/408

The pmf looks same as one i computed using the wikipedia formula. 

The rand(d) function also works as intended. 

Pkg.test("Distributions") pass

Thanks, Gus

### CODE REVIEW

**Comment by lindahua** [comment]
You probably want to add testing cases where `r` is non-integer.

**Comment by augustinyiptong** [comment]
Hello, i have added a test case for non-integer r parameter. Thanks, Gus

**Comment by augustinyiptong** [comment]
Squashed. Thanks

**Comment by andreasnoack** [comment]
Great. Thanks for the contribution.

**Pull request merged**
