### PR TITLE
Make PoissonBinomial support ForwardDiff

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR enables forward differentiation through the `PoissonBinomial` distribution.

### CODE REVIEW

**Comment by matbesancon** [comment]
Hi, thanks for the PR, could you add some tests and verify that all the steps here are made generic (there are some hard-coded zeros)

**Comment by matbesancon** [comment]
bump @mohamed82008 to add a small ForwardDiff test :)

**Comment by mohamed82008** [comment]
Will get to it.

**Comment by mohamed82008** [comment]
I believe this is ready.

**Comment by matbesancon** [comment]
Looks good, merging in 8 hours if no objections

**Pull request merged**
