### PR TITLE
Update README.md (Add a badge for the license)

### PR DESCRIPTION
**Pull request by alexndrejoly**

### CODE REVIEW

**Comment by KristofferC** [comment]
Does this provide any extra information of is it just adding a badge because badges are pretty? Anyone who is interested in the licence can just look at the `LICENSE.md` file.

**Comment by ViralBShah** [comment]
I agree. I think a license badge is not really necessary.

**Comment by ViralBShah** [comment]
I don't mean to discourage the contribution, but just echoing my thoughts here.

**Comment by simonbyrne** [comment]
I don't really see what the licence badge adds.

**Pull request closed without merging**
