### PR TITLE
Wct/refactor mvt

### PR DESCRIPTION
**Pull request by willtebbutt**
Addresses #1158

### CODE REVIEW

**Comment by oxinabox** [comment]
Can this be merged and a release tagged?

**Comment by mschauer** [comment]
Can someone else tag?

**Comment by willtebbutt** [comment]
🤦 I forgot to bump the patch version

**Comment by willtebbutt** [comment]
@mschauer should I open another PR with a patch bump that can be tagged?

**Comment by oxinabox** [comment]
You did bump the patch version AFAICT?

**Comment by oxinabox** [comment]
This seems to be a breaking change.
It removed the `zmean` from the constructor.

**Pull request merged**
