### PR TITLE
 Updating constants.jl - @irrational instead of @math_const

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Thanks for doing this. Let's see what Travis says (and hope Travis isn't wrong).

**Comment by ranjanan** [comment]
It has failed the v0.3.10 test I think, but passed the nightly test. This was expected right? @spencerlyon2

**Comment by spencerlyon2** [comment]
Yes, I think this should be expected because `@irrational` is only defined on 0.4dev.

Getting something into Compat would be the best way to resolve the problem. That entails defining the `@irrational` as an unexported member of `Base` (from within Compat), making a release of Compat, then leveraging the new compat from within distributions.

**Comment by simonster** [comment]
I took a different route in JuliaLang/Compat.jl#109 and defined `Compat.@irrational` instead of mucking with Base. If you change this code to `import Compat.@irrational` it should work once that's merged.

**Comment by ranjanan** [comment]
Cool stuff @simonster . Let's hope Travis passes both tests.

**Comment by IainNZ** [comment]
@simonster can a new version be tagged?

**Comment by simonster** [comment]
Tagged.

**Pull request merged**
