### PR TITLE
Nan checks

### LINKED ISSUE #1055: Checking foo() === NaN is brittle
Tests for Distributions.jl fails on Julia master likely due to the type of NaN that is generated. `===` on NaN will do a bitwise check. It is likely the tests should use `isnan`.

### PR DESCRIPTION
**Pull request by matbesancon**
closes #1055

### CODE REVIEW

**Comment by matbesancon** [comment]
the only problem with these new tests is that it is ignoring the check with the specific NaN we want.
If the compiler infers`NaN`, but we expect `NaN32`, this is not validated anymore

**Comment by ararslan** [comment]
You're still using `@inferred` here though.

**Comment by matbesancon** [comment]
yes so the functions have to be type-stable, but they don't have to return the propagated type (if pdf always returned Float64 regardless of the input type, `@inferred` would work

**Comment by ararslan** [comment]
You can check `isnan(x) && x isa T`

**Comment by matbesancon** [comment]
should be fine now

**Pull request merged**
