### PR TITLE
Fix JuliaStats/Distributions.jl#343

### PR DESCRIPTION
**Pull request by jdrugo**
Uncomments the truncated Normal sampler by Robert (1995).

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Before merging this, I'd like to understand why it was commented out before. Was it purely for performance reasons?

**Comment by simonbyrne** [comment]
It appears to be this commit 8637e3abf8af5535f1470719dc11c1655fef7d4e: @lindahua ?

**Comment by jiahao** [comment]
bump

**Comment by jdrugo** [comment]
Even though issue #343 was closed, the issue itself is not yet fixed.

In addition to this pull request, I would suggest adding.
```
TruncatedNormal(0,1,35,Inf)
TruncatedNormal(0,1,-Inf,-35)
```
to `Distributions.jl/test/continuous_test.lst`, to make sure that the tails are tested. I did not do this, as it requires re-generating `Distributions.jl/test/continuous_test.json`.

**Comment by jmxpearson** [comment]
Given that the code was commented for negligible performance changes but that this sampler is needed for correctness, any objections to merging? 

Would close #343 #493

**Comment by jdrugo** [comment]
I now rebased my branch, and added a separate test for sampling the tails of TruncatedNormal, directly addressing the cases in #343.

**Comment by ararslan** [comment]
LGTM

**Comment by jmxpearson** [comment]
Me, too.

**Comment by simonbyrne** [comment]
Thanks, sorry this languished for so long.

**Comment by nalimilan** [comment]
FWIW, it would be nice to use more descriptive commit titles in the future.

**Pull request merged**
