### PR TITLE
PR: removed Beta from MLE list in docs

### PR DESCRIPTION
**Pull request by BMasinde**
fit_mle not implemented for Beta

### CODE REVIEW

**Comment by matbesancon** [comment]
Indeed. The comment in continous/beta.jl:
`# TODO: add MLE method (should be similar to Dirichlet)`
seems to imply that there is a closed-form solution, which I couldn't seem to find. There is an implementation of `fit` that is closed-form using moments.

To complete this PR, could you either:
1. Remove the "TODO" in beta.jl if the closed-form cannot be implemented or
2. implement the fit_mle if you find one?

Thanks a lot!

**Comment by Dsantra92** [comment]
@matbesancon If you don't have a problem I would like to implement `beta_mle` by Newton's method. Can I take over this issue?

**Comment by matbesancon** [comment]
Yes sure that would be great

**Comment by andreasnoack** [comment]
We've discussed this a couple of times and I don't think it makes sense to hand roll Newton's method implementations unless the method requires specific adjustments for the distribution. If we would like to support of optimizing log-likelihoods without closed form solutions then I think we should add a dependency on an optimization package. The alternative is to delegate general MLE to another package.

**Comment by matbesancon** [comment]
Ok then we can merge this PR and remove the todo in another one

**Pull request merged**
