### PR TITLE
Loosen AbstractMatrix to AbstractVecOrMat in _rand for MvNormalCanon

### LINKED ISSUE #534: should MvNormalCanon `_rand!` accept AbstractVecOrMat?
The current implementation of for MvNormalCanon's `_rand!` in v0.4 is:

```
_rand!(d::MvNormalCanon, x::AbstractMatrix) = add!(unwhiten_winv!(d.J, randn!(x)), d.μ)
```

This is causing problems with the test for ConjugatePriors.jl. Can we change it to  `_rand!(d::MvNormalCanon, x::AbstractVecOrMat)`? I think that still works as intended, but someone who knows their stuff should verify.

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #534. I'm not sure this is the right solution, I just kind of wanted to see what happens.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I think this is right but it would be good with a test.

**Comment by ararslan** [comment]
Agreed, will do. Was trying to check out this branch to test ConjugatePriors with this change, but I can't even install ConjugatePriors...

**Comment by jmxpearson** [comment]
I think there's a method ambiguity for this. I had tried widening this at one point, if I recall, but something goes haywire.

**Comment by tawheeler** [comment]
If you pull ConjugatePriors.jl and remove the REQUIRE bounds it works relatively fine.

**Comment by ararslan** [comment]
Nice, I cloned ConjugatePriors, checked out the branch where I changed the dependency bounds, checked out this branch here, and ran the ConjugatePriors tests. Looks like these PRs together fix it!

**Comment by ararslan** [comment]
Ambiguity errors make the tests here fail on 0.5 and 0.6 though, as @jmxpearson had noted. Not really sure how to address those.

**Comment by ararslan** [comment]
Any suggestions for how to address the ambiguity errors here?

**Comment by jmxpearson** [comment]
Just to outline the problem:
1. Generalizing `_rand!(s::Sampleable{Multivariate}, A::AbstractMatrix)` to `_rand!(s::Sampleable{Multivariate}, A::AbstractVecOrMat)` results in an infinite recursion.
1. Generalizing `_rand!(d::MvNormalCanon, x::AbstractMatrix)` to `_rand!(d::MvNormalCanon, x::AbstractVecOrMat)` leads to the ambiguity mentioned, since there's no `_rand!` defined on vectors.

I think the fastest (but ugly solution) is probably just to duplicate the code (here and for `MvNormal`). Even reshaping Vector `x` to a column vector (in order to reuse current `_rand!` is likely to have problems, since, e.g., (5, 5) * (5, 1) = (5, 1), not (5,).

**Comment by ararslan** [comment]
@jmxpearson Do you mean duplicate the code for
```julia
_rand!(s::Sampleable{Multivariate}, A::AbstractMatrix)
```
to define a separate signature for
```julia
_rand!(s::Sampleable{Multivariate}, A::AbstractVector)
```
?

**Comment by jmxpearson** [comment]
Yes, I think that will do it.

**Comment by ararslan** [comment]
Great. I'll give that a shot once I have some time. Thanks for your help and guidance!

**Comment by ararslan** [comment]
Superseded by #625.

**Pull request closed without merging**
