### PR TITLE
Add `quantile` for `UnivariateMixture`

### PR DESCRIPTION
**Pull request by ForceBru**
Added the `quantile` function for `UnivariateMixture`s using `quantile_bisect`. Inspired by [this blog post](http://www.awebb.info/probability/2017/05/12/quantiles-of-mixture-distributions.html).

### CODE REVIEW

**Comment by devmotion** [comment]
Related: https://github.com/JuliaStats/Distributions.jl/pull/1195

**Comment by ForceBru** [comment]
@devmotion, IMO, one of these should be merged, because:

1. Presumably, it would make plotting univariate  mixture models much easier. Currently, StatsPlots.jl [has to special-case them](https://github.com/JuliaPlots/StatsPlots.jl/issues/448#issuecomment-876003083). With support for quantiles one can just plot from some left quantile to some right one.
2. It's inconvenient that it's not possible to calculate quantiles of mixture models

My main reason for implementing this was plotting: I wanted to create a custom plot with mixtures, but suddenly found that there's no way to easily calculate quantiles of a mixture

**Comment by devmotion** [comment]
Sure, I definitely agree, it would be great since it allows to simplify StatsPlots and is useful in general (I used the algorithm myself in one of my projects recently). However, it would be good to use an improved implementaton, either by adding parts of the other PR here or finishing the other PR.

**Comment by devmotion** [comment]
Closed in favour of https://github.com/JuliaStats/Distributions.jl/pull/1389.

**Pull request closed without merging**
