### PR TITLE
Added rng support to discreteuniform.jl with StatsBase v0.15.0.

### PR DESCRIPTION
**Pull request by rofinn**
Adds support for passing an rng for DiscreteUniform distributions.

### CODE REVIEW

**Comment by ararslan** [comment]
Looks good, thanks! It'd be nice if there were a solid way to test this, but I'm not sure how best to go about that. @nalimilan, any ideas?

**Comment by rofinn** [comment]
Well, the new function definition is getting [covered](https://coveralls.io/builds/11617326/source?filename=src%2Funivariate%2Fdiscrete%2Fdiscreteuniform.jl), but it would be nice to have a way of systematically testing the rand methods. Maybe by using a specific rng seed and hard coding expected values?

**Comment by ararslan** [comment]
That seems reasonable, but IIRC seeded random values from the same generator aren't guaranteed to be the same across Julia versions.

**Comment by rofinn** [comment]
This is outside the scope of this PR (possibly even Distributions.jl), but would it make sense to implement a MockRNG type which can guarantee the sequence across julia versions when testing `rand` methods?

**Comment by ararslan** [comment]
Yeah, perhaps a lightweight package that could be used as a test dependency would be good to have eventually. But in the meantime this PR looks reasonable to me.

**Pull request merged**
