### PR TITLE
matrix-variate uniformity and unit test overhaul

### PR DESCRIPTION
**Pull request by johnczito**
This PR introduces several small changes that enforce more homogeneity among the matrix-variate distributions, and it rewrites the unit tests for the matrix-variates to be more rigorous and unified in the spirit of the unit tests for the univariates.

Uniformity changes include:
  - `error()` -> `throw(...)` in Wisharts;
  - make Wisharts conform to [this](https://github.com/JuliaStats/Distributions.jl/pull/935#discussion_r305331825) standard;
  - `c0` -> `logc0` in Wisharts (**breaking?**);
  - `_logpdf(d, X) = logkernel(d, X) + d.logc0` is now generic, and the distribution-specific primitive for density evaluation is `logkernel()`;
  - Wishart `params` no longer returns integrating constant (**breaking?**);
  - `size(d, i)` is now generic;

Outline of the new unit tests:
  1. Generic set of baseline test functions applied to every distribution (constructed by taking the union of all the checks that were previously included on a copy-paste basis);
  1. test every `MatrixDistribution` against the `UnivariateDistribution` it collapses to in the 1 x 1 case;
  1. test `MatrixNormal` and `MatrixTDist` against the `MultivariateDistribution` they collapse to in the row/column case;
  1. test `Wishart`, `InverseWishart`, and `LKJ` density evaluation against archived `Stan` output;
  1. Miscellaneous tests checking special, distribution-specific properties, including new tests about the marginal distributions of `Wishart` elements.

As a result of updating the unit tests, caught and fixed the following:
  - `InverseWishart` variance was wrong (my bad).

Let me know how I can improve this!

### CODE REVIEW

**Comment by matbesancon** [comment]
I see a bigger diff than it should be (LKJ added in exports while it's already there). Did you merge the latest master into your branch?

**Comment by johnczito** [comment]
That change is just adding it to the listed of "Supported distributions" in the module's docstring, not exporting.

**Comment by matbesancon** [comment]
weird, check the diff online, you'll see other changes that are already merged

**Comment by johnczito** [comment]
I’m not sure what you’re referring to. Where should I look?

**Comment by matbesancon** [comment]
In the files changed

**Comment by johnczito** [comment]
Sorry, I'm not seeing what you're seeing. On my end it looks right.

**Comment by matbesancon** [comment]
image

**Comment by matbesancon** [comment]
do you also have 25 files changed with the same LOC deleted and added?

**Comment by johnczito** [comment]
Those are new changes in that screenshot: changing the order the distributions are listed in the docs and listing `LKJ` in the docstring.

 And no. I add 4 `.R` files and 3 `.json` files to `test/ref`, and I delete the 6 individual test scripts for the matrix-variates and replace them with the one `test/matrixvariates.jl`.

**Pull request merged**
